context:
  version: "3.5.4"

package:
  name: boogie
  version: ${{ version }}

source:
  url: https://github.com/boogie-org/boogie/archive/v${{ version }}.tar.gz
  sha256: b9a7d31253cf60004887c24d92d9d9b636fb37445175c6fc75d5685fc25811b6

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

tests:
  - script:
      - boogie /help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Boogie is a modeling language, intended as a layer on which to build program verifiers for other languages.
  homepage: https://github.com/boogie-org/boogie
  repository: https://github.com/boogie-org/boogie

extra:
  recipe-maintainers:
    - danielnachun
