context:
  version: "3.5.8"

package:
  name: boogie
  version: ${{ version }}

source:
  url: https://github.com/boogie-org/boogie/archive/v${{ version }}.tar.gz
  sha256: 6c964a574a9109c564eb7253aef5c60928a50741905d0ee67ca1ffe4adcbdde6

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet =9
    - nuget-license <4
    - sed
  run:
    - dotnet =9

tests:
  - script:
      - boogie /help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Boogie is a modeling language, intended as a layer on which to build program verifiers for other languages.
  homepage: https://github.com/boogie-org/boogie
  repository: https://github.com/boogie-org/boogie

extra:
  recipe-maintainers:
    - danielnachun
