context:
  version: 3.4.3

package:
  name: boogie
  version: ${{ version }}

source:
  url: https://github.com/boogie-org/boogie/archive/v${{ version }}.tar.gz
  sha256: e5a58d4b0fee61e5ab6b5edf1cabd3a3c4ecc6a42f3c7d5425fd3ed485c5aea3

build:
  number: 1
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

tests:
  - script:
      - boogie /help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Boogie is a modeling language, intended as a layer on which to build program verifiers for other languages.
  homepage: https://github.com/boogie-org/boogie
  repository: https://github.com/boogie-org/boogie

extra:
  recipe-maintainers:
    - danielnachun
